/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Smart.Contracts.Romain;

import Smart.Contracts.Romain.api.routes.Routes;
import Smart.Contracts.Romain.api.services.gestionContrats.GestionQuickSort;
import org.web3j.quicksort.QuickSort;


import static spark.Spark.*;

public class Main {

    public static void main(String[] args) throws Exception {
        new Main();
    }
    public Main(){
       start();
    }

    public void start(){
        port(1234);
        before(((request, response) -> {
            response.type("application/json");
        }));
        Routes.load();
    }

}