/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Smart.Contracts.Romain;

import Smart.Contracts.Romain.Managers.Web3JManager;

public class Main {
    public static void main(String[] args){
        Web3JManager manager = new Web3JManager();
        try{
            manager.setup();
        }catch(Exception e){
            System.out.println("une erreur est survenue lors de la configuration de Web3J");
        }
    }
}