/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Smart.Contracts.Romain;

import org.junit.Test;
import static org.junit.Assert.*;

public class LibraryTest {
    @TestContrat
    public void testSomeLibraryMethod() {

    }
}
